# Generated by Django 5.2.1 on 2025-05-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
