# Generated by Django 5.2.1 on 2025-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
