# Generated by Django 5.2.1 on 2025-05-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
