# Generated by Django 5.2.1 on 2025-06-12 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_healthtip_urgentrequest_certificate_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgentrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='urgentrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='hospital_name',
            field=models.CharField(default='Hospital Name', max_length=200),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='reason',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='urgentrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='next_eligible_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urgentrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
