# Generated by Django 5.2.1 on 2025-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_remove_urgentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentrequest',
            name='hospital_name',
            field=models.CharField(default='Unknown Hospital', max_length=200),
        ),
        migrations.AlterField(
            model_name='urgentrequest',
            name='reason',
            field=models.TextField(default='Not specified'),
        ),
    ]
