# Generated by Django 5.2.1 on 2025-06-12 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_urgentrequest_required_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='units_donated',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
    ]
