# Generated by Django 5.2.1 on 2025-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_donation_blood_group_donation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentrequest',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=3),
        ),
    ]
