# Generated by Django 5.2.1 on 2025-06-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_alter_certificate_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
