# Generated by Django 5.2.1 on 2025-06-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0013_bloodstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodStock',
        ),
    ]
