# Generated by Django 5.2.1 on 2025-06-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_delete_bloodstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
