# Generated by Django 5.2.1 on 2025-06-19 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_alter_donation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='next_eligible_date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='units_donated',
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='document',
            field=models.FileField(upload_to='donation_files/', default='default.pdf'),  # ✅ use a valid default
        ),
        migrations.AddField(
            model_name='donation',
            name='units',
            field=models.PositiveIntegerField(default=1),  # ✅ valid number
        ),
        migrations.AlterField(
            model_name='donation',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
