# Generated by Django 5.2.1 on 2025-06-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0016_remove_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='document',
            field=models.FileField(upload_to='donation_files/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='units',
            field=models.PositiveIntegerField(),
        ),
    ]
