# Generated by Django 5.2.1 on 2025-05-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bloodgropu',
            new_name='bloodgroup',
        ),
    ]
