# Generated by Django 5.2.1 on 2025-05-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
