# Generated by Django 5.2.1 on 2025-05-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_bloodrequest_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='request_date',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='urgency_level',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient_profiles/'),
        ),
    ]
