# Generated by Django 5.2.1 on 2025-05-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_request_date_bloodrequest_requested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bloodgroup',
            new_name='blood_group',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
