# Generated by Django 5.2.1 on 2025-06-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_rename_bloodgroup_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
    ]
