# Generated by Django 5.2.1 on 2025-06-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_bloodrequest_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='units_required',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='urgency_level',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Units Required'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient_profiles/'),
        ),
    ]
