# Generated by Django 5.2.1 on 2025-06-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_remove_bloodrequest_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
