# Generated by Django 5.2.1 on 2025-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_rename_status_bloodrequest_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='quantity',
            new_name='units_required',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
