# Generated by Django 5.2.1 on 2025-06-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0002_bloodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequests',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequests',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequests',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequests',
            name='urgency_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequests',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
