# Generated by Django 5.2.1 on 2025-06-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0004_alter_bloodrequests_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodstock',
            old_name='units_available',
            new_name='quantity',
        ),
        migrations.DeleteModel(
            name='BloodRequests',
        ),
    ]
