# Generated by Django 5.2.1 on 2025-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0005_rename_units_available_bloodstock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
