# Generated by Django 5.2.1 on 2025-06-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0006_alter_bloodstock_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='units_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, unique=True),
        ),
    ]
